[project]
name = "zhitou"
version = "0.1.0"
description = "zhitou mono repo platform"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[tool.uv.workspace]
members = [
  "packages/api",
  "packages/core",
  "packages/database",
  "packages/worker",
]
