[project]
name = "database"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "xujingzhou", email = "max3.xu@outlook.com" }
]
requires-python = ">=3.12"
dependencies = [
    "sqlalchemy>=2.0.44",
]

[project.scripts]
database = "database:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
