[project]
name = "core"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "xujingzhou", email = "max3.xu@outlook.com" }
]
requires-python = ">=3.12"
dependencies = [
    "confz>=2.1.0",
    "python-dotenv>=1.2.1",
]

[project.scripts]
core = "core:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
