[project]
name = "worker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "xujingzhou", email = "max3.xu@outlook.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
worker = "worker:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
