[project]
name = "zhitou_agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "agentscope>=1.0.9",
    "agno>=2.3.21",
    "browser-use>=0.11.2",
    "httpx[socks]>=0.28.1",
    "llama-index>=0.14.10",
    "llama-index-llms-dashscope>=0.5.1",
    "llama-index-llms-openai-like>=0.5.3",
    "playwright>=1.57.0",
    "requests>=2.32.5",
]

[project.scripts]
zhitou_agent = "zhitou_agent:main"
zhitou-agent-cli = "zhitou_agent:cli"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "ipykernel>=7.1.0",
]
